Resources:

  ServicesTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: ${self:custom.uptime.servicesTable.deletionPolicy}
    Properties:
      TableName: ${self:custom.uptime.servicesTable.name}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  MetricsTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: ${self:custom.uptime.metricsTable.deletionPolicy}
    Properties:
      TableName: ${self:custom.uptime.metricsTable.name}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: time
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: time
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
