Resources:

  S3WebsiteBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

Outputs:

  WebsiteBucket:
    Value: !Ref S3WebsiteBucket
    Export:
      Name: "${self:custom.uptime.prefix}-website-bucket"

  WebsiteUrl:
    Value: !GetAtt S3WebsiteBucket.WebsiteURL
    Export:
      Name: "${self:custom.uptime.prefix}-website-url"
