Resources:

  S3StorageBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: ${self:custom.uptime.storageBucket.deletionPolicy}
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 31
            Prefix: responses/

Outputs:

  StorageBucket:
    Value: !Ref S3StorageBucket
    Export:
      Name: "${self:custom.uptime.prefix}-storage-bucket"
