Resources:

  S3WebsiteBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html      
            
  S3WebsiteBucketPolicy: 
    Type: 'AWS::S3::BucketPolicy'
    Properties: 
      Bucket: !Ref S3WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Deny"
            Action:
              - "s3:*"
            Principal: "*"
            Resource:
              - !Join [ "", [ "arn:aws:s3:::", !Ref S3WebsiteBucket ] ]
              - !Join [ "", [ "arn:aws:s3:::", !Ref S3WebsiteBucket, "/*" ] ]
            Condition:
              StringNotEquals:
                aws:sourceVpc:
                  - "${self:custom.uptime.vpc}"

Outputs:

  WebsiteBucket:
    Value: !Ref S3WebsiteBucket
    Export:
      Name: "${self:custom.uptime.prefix}-website-bucket"

  WebsiteUrl:
    Value: !GetAtt S3WebsiteBucket.WebsiteURL
    Export:
      Name: "${self:custom.uptime.prefix}-website-url"
