service:
  name: uptime-app

custom:
  stage: ${opt:stage, self:provider.stage}
  uptime:
    prefix: ${self:service}-${self:custom.stage}
    servicesTable:
      name: ${self:custom.uptime.prefix}-services
      throughput: 5
      deletionPolicy: Retain
    metricsTable:
      name: ${self:custom.uptime.prefix}-metrics
      throughput: 5
      deletionPolicy: Retain

    # vpc: vpc-ea6db38c
    # vpce:

frameworkVersion: ">=1.47.0 <2.0.0"

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: nodejs10.x
  environment:
    SERVICES_TABLE: ${self:custom.uptime.servicesTable.name}
    METRICS_TABLE: ${self:custom.uptime.metricsTable.name}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ ServicesTable, Arn ]
        - "Fn::GetAtt": [ MetricsTable, Arn ]

functions:

  api:
    handler: src/api.handler
    memorySize: 256
    timeout: 6
    events:
      - http: 
          path: / # this matches the base path
          method: ANY
          cors: true
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
          cors: true

  pinger:
    handler: src/pinger.handler
    memorySize: 256
    timeout: 45
    events:
      - schedule:
          name: ${self:custom.uptime.prefix}-scheduled-pinger-1-minute
          description: 'The uptime pinger, which runs checks on a schedule (1 minute)'
          rate: rate(1 minute)
          input:
            rate: 1 minute
      - schedule:
          name: ${self:custom.uptime.prefix}-scheduled-pinger-5-minutes
          description: 'The uptime pinger, which runs checks on a schedule (5 minutes)'
          rate: rate(5 minutes)
          input:
            rate: 5 minutes
      - schedule:
          name: ${self:custom.uptime.prefix}-scheduled-pinger-15-minutes
          description: 'The uptime pinger, which runs checks on a schedule (15 minutes)'
          rate: rate(15 minutes)
          input:
            rate: 15 minutes
      - schedule:
          name: ${self:custom.uptime.prefix}-scheduled-pinger-30-minutes
          description: 'The uptime pinger, which runs checks on a schedule (30 minutes)'
          rate: rate(30 minutes)
          input:
            rate: 30 minutes
      - schedule:
          name: ${self:custom.uptime.prefix}-scheduled-pinger-1-hour
          description: 'The uptime pinger, which runs checks on a schedule (1 hour)'
          rate: rate(1 hour)
          input:
            rate: 1 hour

package:
  individually: true

resources:
  - ${file(src/aws/DynamoDbTables.yaml)}
  - ${file(src/aws/S3Bucket.yaml)}
