service:
  name: uptime-app

custom:
  stage: ${opt:stage, self:provider.stage}
  uptime:
    prefix: ${self:service}-${self:custom.stage}
    table:
      name: ${self:custom.uptime.prefix}
      throughput: 5
      deletionPolicy: Retain
    # vpc: vpc-ea6db38c
    # vpce:

frameworkVersion: ">=1.47.0 <2.0.0"

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: nodejs10.x
  environment:
    DYNAMODB_TABLE: ${self:custom.uptime.table.name}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ DynamoDbTable, Arn ]

functions:

  api:
    handler: src/api.handler
    memorySize: 256
    timeout: 6
    events:
      - http: 
          path: / # this matches the base path
          method: ANY
          cors: true
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
          cors: true

  pinger:
    handler: src/pinger.handler
    memorySize: 256
    timeout: 45
    events:
      - schedule:
          name: ${self:custom.uptime.prefix}-scheduled-pinger
          description: 'This is the core component of the uptime app, which runs checks on a schedule.'
          rate: rate(1 minute)

package:
  individually: true

resources:
  - ${file(src/aws/DynamoDbTable.yaml)}
  - ${file(src/aws/S3Bucket.yaml)}
