Resources:

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
                
  # S3BucketPolicy: 
  #   Type: 'AWS::S3::BucketPolicy'
  #   Properties: 
  #     Bucket: !Ref S3Bucket
  #     PolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: "Deny"
  #           Action:
  #             - "s3:*"
  #           Principal: "*"
  #           Resource:
  #             - !Join [ "", [ "arn:aws:s3:::", !Ref S3Bucket ] ]
  #             - !Join [ "", [ "arn:aws:s3:::", !Ref S3Bucket, "/*" ] ]
  #           Condition:
  #             StringNotEquals:
  #               aws:sourceVpc:
  #                 - "${self:custom.uptime.vpc}"

Outputs:

  WebsiteUrl:
    Value: !GetAtt S3Bucket.WebsiteURL
    Export:
      Name: "${self:service}-${self:custom.stage}-website-url"
