service:
  name: uptime-destroy

custom:
  remover:
    buckets:
      - ${cf:uptime-${self:provider.stage}.WebsiteBucket}

frameworkVersion: ">=1.47.0 <2.0.0"

plugins:
  - serverless-s3-remover

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
