name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Make sure it builds on node ${{ matrix.node_version }} and ${{ matrix.os }} and deploys
    runs-on: ubuntu-latest
    strategy:
      matrix:      
        node-version: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and deploy
      run: |
        npm install
        npm run build
        npm run deploy 
      env:
        CI: true
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
